name: coding-standards-fixer

on:
  workflow_call:
    inputs:
      os:
        description: Os to run the job on, separated by comma.
        required: false
        default: '["ubuntu-latest"]'
        type: string
      php:
        description: PHP versions to test, separated by comma.
        default: '["8.3"]'
        required: false
        type: string

jobs:
  coding-standards:
    name: PHP ${{ matrix.php }}-${{ matrix.os }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: ${{ fromJson(inputs.os) }}
        php: ${{ fromJson(inputs.php) }}

    permissions:
      contents: write

    timeout-minutes: 5
    concurrency:
      cancel-in-progress: true
      group: coding-standards-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}

    steps:
      - name: Set Git To Use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Checkout.
        uses: actions/checkout@v3

      - name: Configure environment
        run: |
          export COMPOSER_ROOT_VERSION=$(/usr/bin/jq --null-input --raw-output 'first(inputs["extra"]["branch-alias"])[]' composer.json)
          echo COMPOSER_ROOT_VERSION=$COMPOSER_ROOT_VERSION >> $GITHUB_ENV

      - name: Setup PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Validate Composer
        run: composer validate

      - name: Get Composer Cache Directory
        # Docs: <https://github.com/actions/cache/blob/master/examples.md#php---composer>
        id: composer-cache
        run: echo "::set-output name=dir::$(composer config cache-files-dir)"

      - name: Restore Composer Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-${{ matrix.php }}-composer

      - name: Install Dependencies
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 5
          max_attempts: 5
          command: composer update --prefer-dist --no-interaction --no-progress

      - name: Fix Code Style
        run: vendor/bin/php-cs-fixer fix --config=.php-cs-fixer.dist.php -vvv --using-cache=no

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: 'style(php-cs-fixer): fix coding standards'
          branch: ${{ github.head_ref }}
          commit_author: 'github-actions <github-actions@users.noreply.github.com>'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
